---
spring:
  profiles: dev-db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/timetable_service?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: bok03220
    password: khb!02030504
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none