# 공통 설정
spring:
  profiles:
    active: dev

server:
  port: 5000


--- #dev 환경
spring.profiles.include: dev-db
spring:
  profiles: dev


--- #real 환경
spring.profiles.include: real-db
spring:
  profiles: real
