# 공통 설정
spring:
  profiles:
    active: real-db

server:
  port: 5000

logging:
  config: classpath:log4j2.yml

--- #dev 환경
spring.profiles.include: dev-db
spring:
  profiles: dev


--- #real 환경
spring.profiles.include: real-db
spring:
  profiles: real
