drop table course if exists
drop table memo if exists
drop table registration_course if exists
drop table user if exists
create table course (id bigint generated by default as identity, building varchar(255), code varchar(255), day_of_week varchar(255), end_time integer not null, professor varchar(255), room varchar(255), start_time integer not null, title varchar(255), primary key (id))
create table memo (id bigint generated by default as identity, content varchar(255), title varchar(255), registration_course_id bigint, primary key (id))
create table registration_course (id bigint generated by default as identity, course_id bigint, user_id bigint, primary key (id))
create table user (id bigint generated by default as identity, primary key (id))
alter table memo add constraint FKhy4fy5s1qvjxvqvl6qrcfvna4 foreign key (registration_course_id) references registration_course
alter table registration_course add constraint FKtj73gfsxbweiulv4qwutagocf foreign key (course_id) references course
alter table registration_course add constraint FK2ld6eixhu9kk8uiqdovhxr97d foreign key (user_id) references userRSET=utf8mb4;